# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSDemoSet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSDemoSet
pod 'MLeaksFinder'
pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'YYModel', '~> 1.0.4'

end
